dist:
  name: otelcol
  description: PeerInfo extension for OpenTelemetry Collector.
  output_path: ./dist

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.137.0
#  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.137.0
#  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.137.0
#  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter v0.137.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.137.0
#  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.137.0

processors:
  - gomod: github.com/hkwi/vardumpprocessor main
  - gomod: github.com/hkwi/mtlsprocessor v0.0.0
    path: ./

extensions:
  # mtlsprocessor depsends on this extension
  - gomod: github.com/hkwi/mtlsauthextension main

